# Generated by Django 4.0.1 on 2022-02-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cottage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('min_size', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('commumication', models.PositiveSmallIntegerField(choices=[(1, 'Электричество'), (2, 'Газ'), (3, 'Вода'), (4, 'Интернет')])),
                ('direct', models.PositiveSmallIntegerField(choices=[(1, 'Симферопольское шоссе'), (2, 'Новорязанское шоссе'), (3, 'Калужское шоссе'), (4, 'Новорижское шоссе')])),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
