# Generated by Django 4.0.1 on 2022-02-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='main_photo',
            field=models.ImageField(default=1, upload_to='main_photos/'),
            preserve_default=False,
        ),
    ]
